# Basic
title: 一休
#subtitle:
description: 免费分享各种好用的工具和教程
welcome_message: 上干货，不废话。
#welcome_message: <a href="#" target="_blank">Download the theme</a>
#creator: <a href="http://xxx.com">@yourID</a>


url: "https://yixiu.scjp.cc"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 点击进入
    description: 一休老家

# Navigation buttons in the front page.
nav:
     - {title: HOME, description: 首页, url: 'https://yixiu.scjp.cc'}

# Pagination
plugins: [jekyll-paginate]
paginate: 8
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: disqusID
    # duoshuo: 
    
# Social
social:
    #weibo:
    github: yixiu001
#    twitter:
#    gplus:
    youtube: yixiu001
    mail: mail@lvyabin.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

# 时区
# timezone: Asia/Shanghai
#timezone: TIMEZONE
